# Generated by Django 2.1.7 on 2019-02-18 17:54

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ended',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='started',
            field=models.FloatField(default=time.time),
        ),
    ]
