# Generated by Django 2.1.7 on 2019-02-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ended',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='started',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='joined',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
