# Generated by Django 2.1.7 on 2019-02-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='history',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='options',
            field=models.TextField(default=None, null=True),
        ),
    ]
