# Generated by Django 2.1.7 on 2019-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0002_auto_20190218_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
