# Generated by Django 2.1.7 on 2019-02-21 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codenamez', '0002_auto_20190221_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
