# Generated by Django 2.1.7 on 2019-02-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0003_auto_20190218_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='game',
            field=models.ForeignKey(blank=True, default='', on_delete=models.SET(''), to='codenamez.Game'),
            preserve_default=False,
        ),
    ]
