# Generated by Django 2.1.7 on 2019-02-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0004_auto_20190218_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ended',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
