# Generated by Django 2.1.7 on 2019-02-18 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0005_auto_20190218_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codenamez.Game'),
        ),
    ]
