# Generated by Django 2.1.7 on 2019-03-19 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codenamez', '0006_auto_20190319_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameList',
            new_name='GamePlayer',
        ),
        migrations.AlterField(
            model_name='gameconnection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
