# Generated by Django 2.1.7 on 2019-02-18 18:14

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0006_auto_20190218_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created',
            field=models.IntegerField(default=time.time),
        ),
        migrations.AlterField(
            model_name='game',
            name='ended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='started',
            field=models.IntegerField(default=time.time),
        ),
    ]
