# Generated by Django 2.1.7 on 2019-02-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0007_auto_20190218_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='started',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
