# Generated by Django 2.1.7 on 2019-03-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0008_gameplayer_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='admin',
            new_name='is_admin',
        ),
    ]
