# Generated by Django 2.1.7 on 2019-03-19 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codenamez', '0009_auto_20190319_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameconnection',
            old_name='user',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='gameplayer',
            old_name='user',
            new_name='player',
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game', 'player')},
        ),
    ]
