# Generated by Django 2.1.7 on 2019-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0010_auto_20190319_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ranking',
            field=models.IntegerField(default=1000),
        ),
    ]
