# Generated by Django 2.1.7 on 2019-03-21 12:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codenamez', '0012_gameplayer_is_spymaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameconnection',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameconnection',
            name='player',
        ),
        migrations.RenameField(
            model_name='gameplayer',
            old_name='player',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game', 'user')},
        ),
        migrations.DeleteModel(
            name='GameConnection',
        ),
    ]
