# Generated by Django 2.1.7 on 2019-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0013_auto_20190321_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='team',
            field=models.IntegerField(default=0),
        ),
    ]
