# Generated by Django 2.1.7 on 2019-03-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0014_auto_20190321_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='history',
            new_name='board',
        ),
        migrations.RemoveField(
            model_name='game',
            name='data',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='selected_cards',
            field=models.TextField(default='null'),
        ),
    ]
