# Generated by Django 2.1.7 on 2019-03-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0015_auto_20190321_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='selected_cards',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='confirmed_turn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.TextField(default='{}'),
        ),
    ]
