# Generated by Django 2.1.7 on 2019-03-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0016_auto_20190321_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='confirmed_turn',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='locked_in',
            field=models.BooleanField(default=False),
        ),
    ]
