# Generated by Django 2.1.7 on 2019-03-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamez', '0018_auto_20190321_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_clue',
            field=models.CharField(default={}, max_length=128),
        ),
    ]
